apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: staybook-gateway
  namespace: edge
  annotations:
    networking.istio.io/service-type: ClusterIP
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: v1
kind: Service
metadata:
  name: staybook-gateway-nodeport
  namespace: edge
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  selector:
    gateway.networking.k8s.io/gateway-name: staybook-gateway
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
