apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: staybook
  namespace: istio-system
spec:
  profile: minimal
  meshConfig:
    accessLogEncoding: JSON
    enableTracing: true
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      concurrency: 1
      proxyStatsMatcher:
        inclusionRegexps:
          - ".*outlier_detection.*"
          - ".*circuit_breakers.*"
          - ".*upstream_rq_retry.*"
          - ".*upstream_rq_pending_overflow.*"
          - ".*upstream_cx_overflow.*"
          - ".*ratelimit.*"
    extensionProviders:
      - name: otel-tracing
        opentelemetry:
          service: otel-collector.observability.svc.cluster.local
          port: 4317
    outboundTrafficPolicy:
      mode: ALLOW_ANY
  components:
    pilot:
      k8s:
        resources:
          requests: {cpu: 100m, memory: 256Mi}
          limits: {memory: 512Mi}
  values:
    global:
      proxy:
        resources:
          requests: {cpu: 20m, memory: 48Mi}
          limits: {memory: 128Mi}
    pilot:
      autoscaleEnabled: false
