apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels: {{- include "svc.labels" . | nindent 4 }}
spec:
  selector: {{- include "svc.selector" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
